spring:
  application:
    name: zipkin
  rabbitmq:
    host: rabbitmq
    username: admin
    password: 123456

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
